// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CRMService
{
    public partial class DeviceType
    {
        public DeviceType()
        {
            Object = new HashSet<Object>();
        }

        public int DeviceTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? OrderNumber { get; set; }
        public string NickName { get; set; }

        public virtual ICollection<Object> Object { get; set; }
    }
}