// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CRMService
{
    public partial class Ep
    {
        public int ProcId { get; set; }
        public int ProcGroupId { get; set; }
        public int? OrderNumber { get; set; }
        public string ComponentGuid { get; set; }
        public int? ProcType { get; set; }
        public string Title { get; set; }
        public int? InternalNumber { get; set; }
        public bool? Enabled { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? RcfilterInterval { get; set; }
        public bool? UseAnyEvent { get; set; }
        public int? ActivationMode { get; set; }
        public bool? AnyEventForActivate { get; set; }
        public int? ActivationInterval { get; set; }
        public bool? AnyEventForDeactivate { get; set; }
        public string Params { get; set; }
    }
}