// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CRMService
{
    public partial class Epcustomer
    {
        public int RecordId { get; set; }
        public int RecordType { get; set; }
        public int OwnerRecordId { get; set; }
        public int? CustomerGroupId { get; set; }
        public int? BeginningNumber { get; set; }
        public int? EndNumber { get; set; }
    }
}