// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CRMService
{
    public partial class EventTemp
    {
        public int EventTemplateId { get; set; }
        public int OrderNumber { get; set; }
        public string EventTemplateName { get; set; }
        public string Description { get; set; }
        public bool RecordDeleted { get; set; }
    }
}