// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CRMService
{
    public partial class ExtField
    {
        public int ExtFieldId { get; set; }
        public int OrderNumber { get; set; }
        public int ExtFieldType { get; set; }
        public string ExtFieldName { get; set; }
        public string Description { get; set; }
        public bool RecordDeleted { get; set; }
    }
}