// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CRMService
{
    public partial class ObjSchedule
    {
        public int RecordId { get; set; }
        public int ObjectId { get; set; }
        public int? DayNumber { get; set; }
        public int? IntervalNumber { get; set; }
        public DateTime? StartDt { get; set; }
        public DateTime? StopDt { get; set; }

        public virtual Object Object { get; set; }
    }
}