// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CRMService
{
    public partial class ObjType
    {
        public int ObjTypeId { get; set; }
        public int OrderNumber { get; set; }
        public string ObjTypeName { get; set; }
        public string Description { get; set; }
        public bool RecordDeleted { get; set; }
    }
}