//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMServiceEntities : DbContext
    {
        public CRMServiceEntities()
            : base("name=CRMServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GuardObject> GuardObject { get; set; }
        public DbSet<Serviceman> Serviceman { get; set; }
        public DbSet<ServicemanExtension> ServicemanExtension { get; set; }
        public DbSet<Serviceorder> Serviceorder { get; set; }
        public DbSet<ServiceorderExtension> ServiceorderExtension { get; set; }
        public DbSet<Systemuser> Systemuser { get; set; }
        public DbSet<GuardObjectExtention> GuardObjectExtention { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserArea> UserArea { get; set; }
        public DbSet<WorkContact> WorkContact { get; set; }
    }
}
