//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPCustomer
    {
        public int RecordID { get; set; }
        public int RecordType { get; set; }
        public int OwnerRecordID { get; set; }
        public Nullable<int> CustomerGroupID { get; set; }
        public Nullable<int> BeginningNumber { get; set; }
        public Nullable<int> EndNumber { get; set; }
    }
}
