//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTemp
    {
        public int EventTemplateID { get; set; }
        public int OrderNumber { get; set; }
        public string EventTemplateName { get; set; }
        public string Description { get; set; }
        public bool RecordDeleted { get; set; }
    }
}
