//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardObjectExtention
    {
        public System.Guid GuardObjectId { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Square { get; set; }
        public string A28Id { get; set; }
        public string NumberHex { get; set; }
        public string ObjectPassword { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public Nullable<int> ControlTime { get; set; }
        public Nullable<bool> IsArm { get; set; }
        public Nullable<bool> IsFire { get; set; }
        public Nullable<bool> IsPanic { get; set; }
        public Nullable<int> ObjTypeId { get; set; }
        public Nullable<int> EventTemplateId { get; set; }
    }
}
