//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjAdmin
    {
        public ObjAdmin()
        {
            this.Object = new HashSet<Object>();
        }
    
        public int ObjAdminID { get; set; }
        public string AdminName { get; set; }
        public string AdminEmail { get; set; }
        public string AdminPhone { get; set; }
        public System.Guid AdminGUID { get; set; }
        public Nullable<System.DateTime> SentInviteDT { get; set; }
        public Nullable<System.DateTime> RegistrationDT { get; set; }
        public bool RecordDeleted { get; set; }
        public string MyAlarmUserID { get; set; }
    
        public virtual ICollection<Object> Object { get; set; }
    }
}
