//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjCust
    {
        public int RecordID { get; set; }
        public int ObjectID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public string ObjCustTitle { get; set; }
        public string ObjCustName { get; set; }
        public string ObjCustPhone1 { get; set; }
        public string ObjCustPhone2 { get; set; }
        public string ObjCustPhone3 { get; set; }
        public string ObjCustPhone4 { get; set; }
        public string ObjCustPhone5 { get; set; }
        public string ObjCustAddress { get; set; }
        public Nullable<int> NordKeyID { get; set; }
        public string PINCode { get; set; }
        public Nullable<bool> IsVisibleInCabinet { get; set; }
        public Nullable<bool> ReclosingRequest { get; set; }
        public Nullable<bool> ReclosingFailure { get; set; }
        public string MyAlarmUserID { get; set; }
        public Nullable<int> MyAlarmUserRole { get; set; }
        public string MyAlarmUserPhone { get; set; }
        public System.Guid ObjCustGUID { get; set; }
        public Nullable<bool> MyAlarmPanicEnabled { get; set; }
    
        public virtual Object Object { get; set; }
    }
}
