//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjExtField
    {
        public int RecordID { get; set; }
        public int ObjectID { get; set; }
        public int ExtFieldID { get; set; }
        public string ExtFieldValue { get; set; }
        public System.Guid ExtFiledValueGUID { get; set; }
    
        public virtual ExtField ExtField { get; set; }
        public virtual Object Object { get; set; }
    }
}
