//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public Object()
        {
            this.ObjExtField = new HashSet<ObjExtField>();
            this.ObjCust = new HashSet<ObjCust>();
        }
    
        public int ObjectID { get; set; }
        public int ObjectNumber { get; set; }
        public int EventTemplateID { get; set; }
        public int ObjTypeID { get; set; }
        public string Name { get; set; }
        public string Contract { get; set; }
        public string ObjectPassword { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Address { get; set; }
        public bool ArmSchedule_EarlyArm { get; set; }
        public bool ArmSchedule_ControlArm { get; set; }
        public bool ArmSchedule_LaterArm { get; set; }
        public bool ArmSchedule_EarlyDisarm { get; set; }
        public bool ArmSchedule_ControlDisarm { get; set; }
        public bool ArmSchedule_LaterDisarm { get; set; }
        public int ArmSchedule_Deviation { get; set; }
        public bool LSchedEnable { get; set; }
        public System.DateTime LSchedStart { get; set; }
        public System.DateTime LSchedStop { get; set; }
        public bool Disable { get; set; }
        public System.DateTime DisableDT { get; set; }
        public bool AutoEnable { get; set; }
        public System.DateTime AutoEnableDT { get; set; }
        public int ControlTime { get; set; }
        public bool ManualDisarm { get; set; }
        public string MapFileName { get; set; }
        public string WebLink { get; set; }
        public bool IsArm { get; set; }
        public bool IsFire { get; set; }
        public bool IsPanic { get; set; }
        public bool CTUseCommon { get; set; }
        public bool CTIgnoreSystemEvent { get; set; }
        public bool IsTestFilter { get; set; }
        public bool IsDoubleFilter { get; set; }
        public bool IsUseEPAF { get; set; }
        public Nullable<int> DeviceTypeID { get; set; }
        public Nullable<bool> IsRadioChannel { get; set; }
        public Nullable<bool> IsPhoneChannel { get; set; }
        public Nullable<bool> IsEthernetChannel { get; set; }
        public Nullable<bool> IsGsmDTMFChannel { get; set; }
        public Nullable<bool> IsGsmGPRSChannel { get; set; }
        public Nullable<bool> IsGsmCSDChannel { get; set; }
        public Nullable<int> RadioTransID { get; set; }
        public string ActionNumber { get; set; }
        public string ChannelPhonePhone { get; set; }
        public Nullable<int> ChannelEthernetProviderID { get; set; }
        public Nullable<int> ChannelGsmOperator1ID { get; set; }
        public Nullable<int> ChannelGsmOperator2ID { get; set; }
        public string ChannelGsmPhone1 { get; set; }
        public string ChannelGsmPhone2 { get; set; }
        public string DeviceSIM1 { get; set; }
        public string DeviceSIM2 { get; set; }
        public Nullable<int> WarnSignalLevel { get; set; }
        public Nullable<int> AlarmSignalLevel { get; set; }
        public Nullable<int> XCoord { get; set; }
        public Nullable<int> YCoord { get; set; }
        public Nullable<bool> CoordVisible { get; set; }
        public Nullable<int> MountingCompanyID { get; set; }
        public Nullable<int> SecurityCompanyID { get; set; }
        public Nullable<int> ServiceCompanyID { get; set; }
        public Nullable<int> MonitoringStateID { get; set; }
        public Nullable<System.DateTime> StartMonitoringDate { get; set; }
        public Nullable<System.DateTime> StopMonitoringDate { get; set; }
        public Nullable<System.DateTime> StateChangeDate { get; set; }
        public Nullable<int> SecurityDogovorID { get; set; }
        public Nullable<int> ReactionDogovorID { get; set; }
        public Nullable<int> PSecurityCompanyID { get; set; }
        public Nullable<int> ReactionCompanyID { get; set; }
        public Nullable<int> MountingPersonID { get; set; }
        public Nullable<int> PServiceCompanyID { get; set; }
        public Nullable<int> TariffID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SecurityStateID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<bool> IsManCaused { get; set; }
        public Nullable<bool> IsAccessControl { get; set; }
        public Nullable<bool> IsServiceAvailable { get; set; }
        public Nullable<bool> IsVitalFunction { get; set; }
        public string CommentForOperator { get; set; }
        public string CommentForGuard { get; set; }
        public string CustomersComment { get; set; }
        public bool RecordDeleted { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string TransmitterID { get; set; }
        public string JupiterDeviceID { get; set; }
        public string JupiterCypherKey { get; set; }
        public string JupiterParams { get; set; }
        public Nullable<int> ObjAdminID { get; set; }
        public string JupiterArmDisarmPassword { get; set; }
        public Nullable<int> DeviceCSN { get; set; }
        public Nullable<int> DeviceArmAllowed { get; set; }
        public Nullable<int> DeviceHWVersion { get; set; }
        public Nullable<int> DeviceSWVersion { get; set; }
        public Nullable<decimal> MoneyBalance { get; set; }
        public Nullable<int> DisableReason { get; set; }
        public Nullable<decimal> ContractPrice { get; set; }
        public int RegionID { get; set; }
        public string DeviceIMEI { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsSecureATM { get; set; }
    
        public virtual ICollection<ObjExtField> ObjExtField { get; set; }
        public virtual ICollection<ObjCust> ObjCust { get; set; }
        public virtual ObjAdmin ObjAdmin { get; set; }
    }
}
