//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceorderExtension
    {
        public System.Guid ServiceorderId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> Serviceman_start { get; set; }
        public Nullable<System.Guid> Serviceman_end { get; set; }
        public Nullable<System.DateTime> Income { get; set; }
        public Nullable<System.DateTime> Outgone { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Category { get; set; }
        public string Who_init { get; set; }
        public Nullable<System.DateTime> Moved { get; set; }
        public string Result { get; set; }
        public Nullable<int> Moved_reason { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<System.Guid> GuardObjectId { get; set; }
    }
}
