//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Systemuser
    {
        public System.Guid SystemuserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ADName { get; set; }
    }
}
