//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkContact
    {
        public int Id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string birthday { get; set; }
        public string email { get; set; }
        public string company { get; set; }
        public string department { get; set; }
        public string workphone { get; set; }
        public string homephone { get; set; }
        public string servicephone { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string idx { get; set; }
        public Nullable<bool> status { get; set; }
        public string workplace { get; set; }
    }
}
